### ISSUE TITLE
从LiteLoaderQQNT的插件商店无法安装并报错

### ISSUE THREAD

**Issue by TranscendMa** [PRO-2684/pURLfy#1]
系统环境：WIN11 专工23H2 中文版
LiteLoader目录位置：D:\Apps\Social\QQ\resources\app\LiteLoaderQQNT-main
QQ本体安装位置：D:\Apps\Social\QQ

在以上位置安装了QQ和liteloader，并从插件商店安装时，报错显示如下：
![屏幕截图 2024-04-15 193942](https://github.com/PRO-2684/pURLfy/assets/121599515/9e449ffc-f910-45cf-af81-a5bbb65265f1)
以及提示：“安装包异常，可能是作者未正确配置”
应该是路径问题导致无法正常安装。早些时候在安装其他插件时也遇到无法安装的问题，重启QQ后得到解决。
在安装本插件失败后，手动删除了.\plugins下pURLfy创建的文件夹，再度安装依旧报错

**Comment by PRO-2684** [comment]
之前配置有问题，请前往 https://github.com/PRO-2684/LiteLoaderQQNT-pURLfy 安装插件
