### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by clansty** [PRO-2684/pURLfy#6]
建议将此包以及规则包发布到 npmjs.org 以方便基于 NodeJS 构建的项目使用。另外建议提供 TypeScript 类型定义文件

**Comment by PRO-2684** [comment]
[npm 已发布](https://www.npmjs.com/package/purlfy)，但是 TypeScript 对我来说还是太头痛了。现已添加相关 JSDoc 注释，希望能帮到你。
